/**
 * Barrel for the admin app's centralized types — import from `@/types`.
 * Component prop types (`XxxProps`) live in a per-feature file here; no
 * component declares its props inline (root §13.4, §16.6).
 */
export * from "./admin-settings"
export * from "./admins"
export * from "./agent"
export * from "./aml"
export * from "./approvals"
export * from "./assets"
export * from "./audit"
export * from "./blocked"
export * from "./capabilities"
export * from "./compliance"
export * from "./currencies"
export * from "./dashboard"
export * from "./data-table"
export * from "./flags"
export * from "./flows"
export * from "./kyc"
export * from "./ledger"
export * from "./limits"
export * from "./metrics"
export * from "./notifications"
export * from "./ops"
export * from "./pricing"
export * from "./providers"
export * from "./reconciliation"
export * from "./sanctions"
export * from "./settings"
export * from "./shared"
export * from "./shell"
export * from "./templates"
export * from "./tickets"
export * from "./transactions"
export * from "./treasury"
export * from "./user-detail"
export * from "./users"
export * from "./webhooks"
export * from "./whatsapp"
