/**
 * DI token and port contract for the payment (fiat pay-in) provider.
 *
 * Flutterwave is the concrete adapter at launch (NGN virtual-account
 * collection). The execution engine depends only on this interface so the
 * provider can be swapped without touching callers.
 *
 * ADR-0006: Flutterwave chosen for NGN collection. Webhook auth is plain
 * constant-time equality of the `verif-hash` header to the configured secret
 * (Flutterwave v3, NOT HMAC).
 */
export const PAYMENT_PROVIDER = Symbol('PAYMENT_PROVIDER');

// ---------------------------------------------------------------------------
// createCollection
// ---------------------------------------------------------------------------

export interface CreateCollectionInput {
  /** Fiat amount to collect (decimal string, e.g. "50000"). */
  amount: string;
  /** ISO-4217 currency code (e.g. "NGN"). Threaded from the stored quote — not hardcoded. */
  currency: string;
  /** Unique transaction reference generated by the engine (idempotency key). */
  reference: string;
  customer: {
    email: string;
    firstname: string;
    lastname: string;
    phone?: string;
  };
}

export interface CreateCollectionOutput {
  /** Virtual account number to display to the user. */
  accountNumber: string;
  /** Bank name for the virtual account. */
  bankName: string;
  /** Provider-scoped reference (Flutterwave flw_ref). */
  providerRef: string;
  /** ISO-8601 expiry datetime string, if the provider includes one. */
  expiresAt?: string;
}

// ---------------------------------------------------------------------------
// verify (pay-in)
// ---------------------------------------------------------------------------

export interface VerifyOutput {
  status: 'successful' | 'pending' | 'failed';
  /** Amount as returned by the provider (decimal string). */
  amount: string;
  currency: string;
  /** Provider-scoped transaction reference (flw_ref). */
  providerRef: string;
}

// ---------------------------------------------------------------------------
// createPayout (pay-out / sell off-ramp)
// ---------------------------------------------------------------------------

export interface CreatePayoutInput {
  /** Fiat amount to disburse (decimal string, e.g. "25000"). Coerced to number at the boundary. */
  amount: string;
  /** ISO-4217 currency code. Threaded from the stored quote — not hardcoded. */
  currency: string;
  /** Unique payout reference generated by the engine (idempotency key). Flutterwave deduplicates on this. */
  reference: string;
  bankAccount: {
    accountNumber: string;
    /** Flutterwave bank code (e.g. "044" for Access Bank). */
    bankCode: string;
    accountName: string;
  };
}

export interface CreatePayoutOutput {
  /** Flutterwave transfer id (stringified for uniformity). */
  providerRef: string;
  /** Initial status returned synchronously. NEW/PENDING → 'pending'; only SUCCESSFUL → 'successful'. */
  status: 'successful' | 'pending' | 'failed';
}

// ---------------------------------------------------------------------------
// verifyPayout (pay-out)
// ---------------------------------------------------------------------------

export interface VerifyPayoutOutput {
  status: 'successful' | 'pending' | 'failed';
  /** Amount as returned by the provider (decimal string). */
  amount: string;
  currency: string;
  /** Flutterwave transfer id (stringified). */
  providerRef: string;
}

// ---------------------------------------------------------------------------
// IPaymentProvider
// ---------------------------------------------------------------------------

export interface IPaymentProvider {
  /**
   * Creates an NGN virtual account (dynamic collection) for a buy order.
   * Returns the account details to display to the user.
   */
  createCollection(
    input: CreateCollectionInput,
  ): Promise<CreateCollectionOutput>;

  /**
   * Verifies a payment by its transaction reference.
   * ALWAYS called server-side before treating any payment as settled.
   * Only `status === 'successful'` with matching amount/currency is a
   * confirmed payment.
   */
  verify(reference: string): Promise<VerifyOutput>;

  /**
   * Initiates an NGN bank transfer (sell off-ramp payout) via Flutterwave
   * Transfers API. POST /transfers.
   *
   * Deduplication: Flutterwave rejects duplicate `reference` values — the
   * caller MUST generate a stable, unique reference per payout attempt.
   * Only `status === 'successful'` is a confirmed disbursement; NEW and
   * PENDING are intermediate states.
   */
  createPayout(input: CreatePayoutInput): Promise<CreatePayoutOutput>;

  /**
   * Fetches the current status of a payout by the Flutterwave transfer id
   * (providerRef returned from `createPayout`). GET /transfers/{id}.
   *
   * Only `status === 'successful'` is the paid terminal state.
   */
  verifyPayout(providerRef: string): Promise<VerifyPayoutOutput>;

  /**
   * Validates the Flutterwave webhook `verif-hash` header (v3 constant-time
   * equality — NOT HMAC). Returns false for any falsy / non-string value
   * (array of strings, undefined, empty) or mismatched secret.
   */
  verifyWebhookSignature(headerValue: string | string[] | undefined): boolean;
}
