/**
 * DI token and port contract for the payment (fiat pay-in) provider.
 *
 * Flutterwave is the concrete adapter at launch (NGN virtual-account
 * collection). The execution engine depends only on this interface so the
 * provider can be swapped without touching callers.
 *
 * ADR-0006: Flutterwave chosen for NGN collection. Webhook auth is plain
 * constant-time equality of the `verif-hash` header to the configured secret
 * (Flutterwave v3, NOT HMAC).
 */
export const PAYMENT_PROVIDER = Symbol('PAYMENT_PROVIDER');

// ---------------------------------------------------------------------------
// createCollection
// ---------------------------------------------------------------------------

export interface CreateCollectionInput {
  /** NGN amount to collect (decimal string, e.g. "50000"). */
  amount: string;
  currency: 'NGN';
  /** Unique transaction reference generated by the engine (idempotency key). */
  reference: string;
  customer: {
    email: string;
    firstname: string;
    lastname: string;
    phone?: string;
  };
}

export interface CreateCollectionOutput {
  /** Virtual account number to display to the user. */
  accountNumber: string;
  /** Bank name for the virtual account. */
  bankName: string;
  /** Provider-scoped reference (Flutterwave flw_ref). */
  providerRef: string;
  /** ISO-8601 expiry datetime string, if the provider includes one. */
  expiresAt?: string;
}

// ---------------------------------------------------------------------------
// verify
// ---------------------------------------------------------------------------

export interface VerifyOutput {
  status: 'successful' | 'pending' | 'failed';
  /** Amount as returned by the provider (decimal string). */
  amount: string;
  currency: string;
  /** Provider-scoped transaction reference (flw_ref). */
  providerRef: string;
}

// ---------------------------------------------------------------------------
// IPaymentProvider
// ---------------------------------------------------------------------------

export interface IPaymentProvider {
  /**
   * Creates an NGN virtual account (dynamic collection) for a buy order.
   * Returns the account details to display to the user.
   */
  createCollection(
    input: CreateCollectionInput,
  ): Promise<CreateCollectionOutput>;

  /**
   * Verifies a payment by its transaction reference.
   * ALWAYS called server-side before treating any payment as settled.
   * Only `status === 'successful'` with matching amount/currency is a
   * confirmed payment.
   */
  verify(reference: string): Promise<VerifyOutput>;

  /**
   * Validates the Flutterwave webhook `verif-hash` header (v3 constant-time
   * equality — NOT HMAC). Returns false for any falsy / non-string value
   * (array of strings, undefined, empty) or mismatched secret.
   */
  verifyWebhookSignature(headerValue: string | string[] | undefined): boolean;
}
