/**
 * Zustand chat store — Phase 9 of the Handshake Agent prototype.
 *
 * SACROSANCT INVARIANT (CLAUDE.md §3.1):
 * `pinComplete()` is the ONLY method that may append a receipt-kind message
 * and open the success overlay. No other action on this path (send, openConfirm,
 * confirmToPin, pressPin before the 4th digit) may ever produce a receipt.
 *
 * Real buy flow (authenticated):
 *   openConfirm → confirmToPin (calls authorizeProposal, stores directiveId+nonce)
 *   → pressPin × 4 → pinComplete (calls executeProposal with PIN)
 *   → on settle: appends pay-in card, polls getTransaction
 *   → on completed: appends full receipt card, opens success overlay
 *
 * Architecture notes:
 * - `createChatStore` is the testable vanilla factory (no React dependency).
 *   Tests inject `schedule: (fn) => fn()` so timers run synchronously.
 * - `useChatStore` is the module-default React binding (singleton store).
 * - Message IDs are generated by a per-store incrementing counter — no
 *   Math.random / Date (non-deterministic, disallowed per spec).
 */

import { createStore } from "zustand/vanilla"
import { useStore } from "zustand"
import {
  buildResponse,
  buildReceipt,
  startChips,
  chipLabel,
} from "@/lib/chat/flow"
import { parseIntent } from "@/lib/chat/intent"
import { mapOutcomeToMessages } from "@/lib/chat/agent-outcome"
import { GREETING_M, GREETING_D } from "@/lib/constants"
import { formatNGN } from "@/lib/format"
import type {
  ChatAction,
  ChatMessage,
  ChatSurface,
  ConfirmPayload,
} from "@/lib/schemas"
import { sendChatMessage as defaultSendChatMessage } from "@/lib/api/chat"
import type {
  WebChatResponse,
  ChatMessageRequest,
  ChatHistoryItem,
  AuthorizeProposalResponse,
  ExecuteProposalResponse,
  TransactionStatusResponse,
} from "@handshake-agent/contracts"
import { getDeviceFingerprint } from "@/lib/device"

// Re-export chipLabel so components can import it from the store module if needed.
export { chipLabel }

/** Milliseconds before the success overlay auto-dismisses. Matches prototype (line 1352). */
const SUCCESS_DISMISS_MS = 1150

/** Poll interval (ms) for settling transactions. */
const POLL_INTERVAL_MS = 3000

// ─── Completion-receipt helpers (shared by buy / sell / send) ─────────────────

const COMPLETION_SUCCESS_LABEL: Record<ChatAction, string> = {
  buy: "Purchase complete",
  sell: "Sale complete",
  send: "Transfer sent",
  swap: "Swap complete",
  ticket: "Ticket confirmed",
  receive: "Deposit address shown",
  balance: "Balance loaded",
}

/**
 * Builds the kind:"receipt" body (sans id/role) for a completed transaction.
 * Buy uses the on-chain amounts the status endpoint returns; sell/send fall
 * back to the confirmed proposal amounts (`pending`) since the sell payout /
 * send total are not echoed on the status payload.
 */
function buildCompletionReceipt(
  action: ChatAction,
  pending: ConfirmPayload,
  tx: TransactionStatusResponse
) {
  const date = new Date(tx.createdAt).toLocaleString("en-NG")
  const txRef = tx.receiptNumber
    ? `REF · ${tx.receiptNumber}`
    : `TX · ${tx.id.slice(0, 8)}`

  if (action === "sell") {
    return {
      kind: "receipt" as const,
      title: "Sale complete",
      subtitle: "Funds sent to your bank account",
      amount: pending.totalValue,
      rows: [
        ...pending.rows.filter((r) => r.label !== "Rate").slice(0, 2),
        { label: "Date", value: date },
      ],
      txRef,
    }
  }

  if (action === "send") {
    return {
      kind: "receipt" as const,
      title: "Transfer sent",
      subtitle: "Your crypto is on its way",
      amount: pending.heroAmount,
      rows: [
        pending.toValue
          ? { label: "To", value: pending.toValue }
          : (pending.rows[0] ?? { label: "Sent", value: pending.heroAmount }),
        { label: "Date", value: date },
      ],
      txRef,
    }
  }

  // buy
  return {
    kind: "receipt" as const,
    title: "Purchase complete",
    subtitle: "USDT credited to your wallet",
    amount: tx.cryptoAmount
      ? `+ ${tx.cryptoAmount} ${tx.asset ?? ""}`
      : pending.heroAmount,
    rows: [
      {
        label: "Paid",
        value: tx.fiatAmount ? formatNGN(tx.fiatAmount) : pending.totalValue,
      },
      { label: "Date", value: date },
    ],
    txRef,
  }
}

// ─── Scheduler type ───────────────────────────────────────────────────────────

/** A function that schedules `fn` to run after a typing delay (or immediately in tests). */
type Scheduler = (fn: () => void) => void

// ─── API adapters injected for testing ────────────────────────────────────────

interface ChatApis {
  chatApi?: (body: ChatMessageRequest) => Promise<WebChatResponse>
  authorizeApi?: (proposalId: string) => Promise<AuthorizeProposalResponse>
  executeApi?: (
    proposalId: string,
    body: {
      directiveId: string
      nonce: string
      pin: string
      deviceFingerprint?: string
      idempotencyKey: string
    }
  ) => Promise<ExecuteProposalResponse>
  pollApi?: (transactionId: string) => Promise<TransactionStatusResponse>
}

// ─── State interface ──────────────────────────────────────────────────────────

type OverlaySurface = ChatSurface

interface ChatState {
  // Per-surface state
  threads: Record<ChatSurface, ChatMessage[]>
  chips: Record<ChatSurface, ChatAction[]>
  typing: Record<ChatSurface, boolean>
  input: Record<ChatSurface, string>

  // Overlay state — one overlay at a time, surface-tracked
  pending: ConfirmPayload | null
  overlaySurface: OverlaySurface
  confirmOpen: boolean
  pinOpen: boolean
  pin: string
  successOpen: boolean
  successText: string
  successSurface: OverlaySurface

  // PIN error state — shown on the pin pad after a wrong PIN / expired directive
  pinError: string | null

  // Live agent proposal tracking
  pendingProposalId: string | null

  // Authorize step — stored between confirmToPin and pinComplete
  _directiveId: string | null
  _nonce: string | null
  _idempotencyKey: string | null

  // Settling: track the transaction being polled
  _pollingTransactionId: string | null

  // Per-surface flag: server history is hydrated once so re-renders / tab
  // switches don't re-append the thread.
  historyHydrated: Record<ChatSurface, boolean>

  // The last money-intent text the user sent — re-sent (with a beneficiaryId)
  // by resolveBeneficiary after they add a payout destination.
  _lastIntentText: string | null

  // Actions
  send(surface: ChatSurface, text: string, action?: ChatAction): void
  sendToAgent(
    surface: ChatSurface,
    text: string,
    beneficiaryId?: string
  ): Promise<void>
  /**
   * Rebuild the thread from persisted server history (GET /chat/messages).
   * Idempotent per surface. Maps each turn with the same `mapOutcomeToMessages`
   * the live send uses, so reloaded cards match live cards. Never appends a
   * receipt (§3.1) and never touches overlay/pin state.
   */
  hydrateHistory(surface: ChatSurface, items: ChatHistoryItem[]): void
  /**
   * Re-sends the last money request with a newly added/selected beneficiaryId
   * so the sell/send proposal can be created. Called from the needs_beneficiary
   * card once the user adds or picks a payout destination.
   */
  resolveBeneficiary(surface: ChatSurface, beneficiaryId: string): Promise<void>
  setInput(surface: ChatSurface, value: string): void
  openConfirm(surface: ChatSurface, payload: ConfirmPayload): void
  cancel(): void
  /**
   * Calls authorizeProposal (authenticated flow) or falls back to PIN immediately
   * (mock/unauthenticated flow). Updates _directiveId + _nonce on success.
   */
  confirmToPin(): Promise<void>
  pressPin(digit: string): void
  pinBack(): void
  /** THE ONLY method that appends a receipt-kind message. */
  pinComplete(): Promise<void>
  reset(surface: ChatSurface): void
}

// ─── Options ──────────────────────────────────────────────────────────────────

interface CreateChatStoreOptions {
  /** Inject a custom scheduler. Default: `(fn) => setTimeout(fn, 680)`. */
  schedule?: Scheduler
  /**
   * Inject mock API functions for testing without module-level mocking.
   * Defaults to the real implementations from `@/lib/api/chat`.
   */
  chatApi?: (body: ChatMessageRequest) => Promise<WebChatResponse>
  authorizeApi?: ChatApis["authorizeApi"]
  executeApi?: ChatApis["executeApi"]
  pollApi?: ChatApis["pollApi"]
}

// ─── Factory ──────────────────────────────────────────────────────────────────

/**
 * Create a vanilla Zustand chat store.
 * Returns a `StoreApi<ChatState>` — use `.getState()` / `.setState()` / `.subscribe()`.
 *
 * @example (test)
 *   const store = createChatStore({ schedule: (fn) => fn() })
 *   store.getState().send("m", "Buy ₦50,000 of USDT", "buy")
 */
export function createChatStore(options: CreateChatStoreOptions = {}) {
  const schedule: Scheduler = options.schedule ?? ((fn) => setTimeout(fn, 680))
  const chatApiFn = options.chatApi ?? defaultSendChatMessage

  // Lazy-import the real API functions so tests can inject mocks without
  // bundling the axios client. These are only called when the injected
  // override is absent — i.e. in the real app.
  const getAuthorizeFn = (): ChatApis["authorizeApi"] => {
    if (options.authorizeApi) return options.authorizeApi
    // Dynamic require to stay CJS-safe in tests; in the real app this is
    // bundled as ESM.  We import the module and pull the named export.
    return (proposalId: string) =>
      import("@/lib/api/chat").then((m) => m.authorizeProposal(proposalId))
  }

  const getExecuteFn = (): ChatApis["executeApi"] => {
    if (options.executeApi) return options.executeApi
    return (proposalId, body) =>
      import("@/lib/api/chat").then((m) => m.executeProposal(proposalId, body))
  }

  const getPollFn = (): ChatApis["pollApi"] => {
    if (options.pollApi) return options.pollApi
    return (txId: string) =>
      import("@/lib/api/chat").then((m) => m.getTransaction(txId))
  }

  // Per-store monotonic counter — deterministic, no Math.random / Date.
  let _idCounter = 0
  function nextId(): string {
    return `msg-${++_idCounter}`
  }

  /** Build the initial greeting message for a surface. */
  function greetingMessage(text: string): ChatMessage {
    return { id: nextId(), role: "assistant", kind: "text", text }
  }

  const greetingM = greetingMessage(GREETING_M)
  const greetingD = greetingMessage(GREETING_D)

  return createStore<ChatState>()((set, get) => ({
    // ── Initial state ──────────────────────────────────────────────────────────
    threads: {
      m: [greetingM],
      d: [greetingD],
    },
    chips: {
      m: startChips(),
      d: startChips(),
    },
    typing: { m: false, d: false },
    input: { m: "", d: "" },

    pending: null,
    overlaySurface: "m",
    confirmOpen: false,
    pinOpen: false,
    pin: "",
    successOpen: false,
    successText: "",
    successSurface: "m",

    pinError: null,

    pendingProposalId: null,

    _directiveId: null,
    _nonce: null,
    _idempotencyKey: null,
    _pollingTransactionId: null,
    historyHydrated: { m: false, d: false },
    _lastIntentText: null,

    // ── Actions ────────────────────────────────────────────────────────────────

    hydrateHistory(surface, items) {
      if (get().historyHydrated[surface]) return

      const built: ChatMessage[] = []
      let lastProposalId: string | null = null
      for (const item of items) {
        built.push({
          id: nextId(),
          role: "user",
          kind: "text",
          text: item.userText,
        })
        if (item.outcome) {
          const { messages, proposalId } = mapOutcomeToMessages(
            item.outcome,
            nextId
          )
          built.push(...messages)
          if (proposalId) lastProposalId = proposalId
        }
      }

      set((s) => {
        // Keep the greeting at index 0; insert reconstructed history after it,
        // before any messages already added live this session.
        const [greeting, ...rest] = s.threads[surface]
        return {
          threads: {
            ...s.threads,
            [surface]: [greeting, ...built, ...rest],
          },
          historyHydrated: { ...s.historyHydrated, [surface]: true },
          ...(lastProposalId ? { pendingProposalId: lastProposalId } : {}),
        }
      })
    },

    async sendToAgent(surface, text, beneficiaryId) {
      const trimmed = text.trim()
      if (!trimmed) return

      // Remember the text so resolveBeneficiary can re-send it once the user
      // adds the payout destination a sell/send needs.
      set({ _lastIntentText: trimmed })

      const userMsg: ChatMessage = {
        id: nextId(),
        role: "user",
        kind: "text",
        text: trimmed,
      }

      set((s) => ({
        threads: { ...s.threads, [surface]: [...s.threads[surface], userMsg] },
        chips: { ...s.chips, [surface]: [] },
        typing: { ...s.typing, [surface]: true },
      }))

      try {
        const response = await chatApiFn(
          beneficiaryId ? { text: trimmed, beneficiaryId } : { text: trimmed }
        )
        const { outcome } = response

        // Shared mapping — identical to the reload/hydration path so a live reply
        // and a reloaded reply render the same. Never produces a receipt (§3.1).
        const { messages, proposalId } = mapOutcomeToMessages(outcome, nextId)
        if (proposalId) {
          // Stash proposalId for the future execute phase.
          set({ pendingProposalId: proposalId })
        }

        set((s) => ({
          threads: {
            ...s.threads,
            [surface]: [...s.threads[surface], ...messages],
          },
          typing: { ...s.typing, [surface]: false },
          chips: { ...s.chips, [surface]: startChips() },
        }))
      } catch {
        const errMsg: ChatMessage = {
          id: nextId(),
          role: "assistant",
          kind: "text",
          text: "I'm having trouble reaching the assistant right now — please try again.",
        }
        set((s) => ({
          threads: {
            ...s.threads,
            [surface]: [...s.threads[surface], errMsg],
          },
          typing: { ...s.typing, [surface]: false },
          chips: { ...s.chips, [surface]: startChips() },
        }))
      }
    },

    async resolveBeneficiary(surface, beneficiaryId) {
      const { _lastIntentText } = get()
      if (!_lastIntentText) return
      await get().sendToAgent(surface, _lastIntentText, beneficiaryId)
    },

    send(surface, text, explicitAction) {
      const trimmed = text.trim()
      if (!trimmed) return

      const action: ChatAction | null = explicitAction ?? parseIntent(trimmed)

      // Append the user message immediately.
      const userMsg: ChatMessage = {
        id: nextId(),
        role: "user",
        kind: "text",
        text: trimmed,
      }

      set((s) => ({
        threads: {
          ...s.threads,
          [surface]: [...s.threads[surface], userMsg],
        },
        chips: { ...s.chips, [surface]: [] },
        typing: { ...s.typing, [surface]: true },
      }))

      if (action) {
        schedule(() => {
          const { messages } = buildResponse(action)
          const assembled: ChatMessage[] = messages.map((m) => ({
            ...m,
            id: nextId(),
            role: "assistant" as const,
          }))

          // Follow-up chips: clear them while a quote is pending (quote actions);
          // restore startChips for non-quote actions (balance/receive/ticket).
          const hasQuote = assembled.some((m) => m.kind === "quote")
          const followUpChips = hasQuote ? [] : startChips()

          set((s) => ({
            threads: {
              ...s.threads,
              [surface]: [...s.threads[surface], ...assembled],
            },
            typing: { ...s.typing, [surface]: false },
            chips: { ...s.chips, [surface]: followUpChips },
          }))
        })
      } else {
        // Fallback: no recognised intent — generic assistant reply.
        schedule(() => {
          const fallbackMsg: ChatMessage = {
            id: nextId(),
            role: "assistant",
            kind: "text",
            text: "I didn't quite catch that. Try asking me to buy crypto, send money, check your balance, or find an event ticket.",
          }
          set((s) => ({
            threads: {
              ...s.threads,
              [surface]: [...s.threads[surface], fallbackMsg],
            },
            typing: { ...s.typing, [surface]: false },
            chips: { ...s.chips, [surface]: startChips() },
          }))
        })
      }
    },

    setInput(surface, value) {
      set((s) => ({ input: { ...s.input, [surface]: value } }))
    },

    openConfirm(surface, payload) {
      set({
        pending: payload,
        overlaySurface: surface,
        confirmOpen: true,
        pinError: null,
        _directiveId: null,
        _nonce: null,
        _idempotencyKey: null,
      })
    },

    cancel() {
      set({
        confirmOpen: false,
        pinOpen: false,
        pin: "",
        pending: null,
        pinError: null,
        _directiveId: null,
        _nonce: null,
        _idempotencyKey: null,
      })
    },

    /**
     * Transition from confirm sheet to PIN pad.
     *
     * Authenticated path: calls authorizeProposal(pendingProposalId) first.
     * On success, stores directiveId + nonce + fresh idempotencyKey, then
     * opens the PIN pad. On failure, surface the error on the confirm sheet
     * and keep it open so the user can retry or cancel.
     *
     * Mock/unauthenticated path: pendingProposalId is null → open PIN directly.
     */
    async confirmToPin() {
      const { pendingProposalId } = get()

      // Mock/offline path (no live proposal): skip authorize, open PIN directly.
      if (!pendingProposalId) {
        set({ confirmOpen: false, pinOpen: true, pin: "", pinError: null })
        return
      }

      try {
        const authorizeFn = getAuthorizeFn()!
        const result = await authorizeFn(pendingProposalId)
        set({
          confirmOpen: false,
          pinOpen: true,
          pin: "",
          pinError: null,
          _directiveId: result.directiveId,
          _nonce: result.nonce,
          // Generate idempotencyKey once per confirm attempt — reused on retry
          _idempotencyKey: crypto.randomUUID(),
        })
      } catch (err) {
        // Show error on the confirm sheet; do NOT open the PIN pad.
        const message =
          err instanceof Error
            ? err.message
            : "Authorization failed. Please try again."
        set({ pinError: message })
      }
    },

    pressPin(digit) {
      const { pin } = get()
      // Ignore if already 4 digits — this guard is checked against the current
      // pin length BEFORE appending, so pressing a 5th digit when pin === "1234"
      // (length 4) is ignored. After pinComplete() runs, pin resets to "" so
      // subsequent presses start a fresh entry.
      if (pin.length >= 4) return
      const next = pin + digit
      set({ pin: next })
      if (next.length === 4) {
        void get().pinComplete()
      }
    },

    pinBack() {
      set((s) => ({ pin: s.pin.slice(0, -1) }))
    },

    /**
     * THE ONLY path that appends a receipt-kind message and opens success.
     * Called automatically when the 4th PIN digit is pressed.
     *
     * Authenticated path: calls executeProposal with PIN + directive credentials.
     * - status:"settling" + payment → appends pay-in card, starts polling.
     * - status:"completed" → appends full receipt, opens success overlay.
     * - Wrong PIN / expired / locked → clears PIN, shows error on PIN pad, keeps proposal.
     *
     * Mock/offline path (_directiveId is null): appends fixture receipt immediately.
     */
    async pinComplete() {
      const {
        pending,
        overlaySurface,
        pendingProposalId,
        _directiveId,
        _nonce,
        _idempotencyKey,
        pin,
      } = get()
      if (!pending) return

      // ── Mock/offline path ────────────────────────────────────────────────────
      if (!pendingProposalId || !_directiveId || !_nonce || !_idempotencyKey) {
        const receipt: ChatMessage = {
          ...buildReceipt(pending.action, pending.meta),
          id: nextId(),
          role: "assistant",
        }

        const successText = COMPLETION_SUCCESS_LABEL[pending.action] ?? "Done"

        set((s) => ({
          threads: {
            ...s.threads,
            [overlaySurface]: [...s.threads[overlaySurface], receipt],
          },
          chips: { ...s.chips, [overlaySurface]: startChips() },
          pinOpen: false,
          pin: "",
          confirmOpen: false,
          pending: null,
          pendingProposalId: null,
          pinError: null,
          _directiveId: null,
          _nonce: null,
          _idempotencyKey: null,
          successOpen: true,
          successText,
          successSurface: overlaySurface,
        }))

        setTimeout(() => {
          set({ successOpen: false })
        }, SUCCESS_DISMISS_MS)
        return
      }

      // ── Authenticated path ───────────────────────────────────────────────────
      // Close the PIN pad immediately (provides instant feedback)
      set({ pinOpen: false, pin: "" })

      try {
        const executeFn = getExecuteFn()!
        const result = await executeFn(pendingProposalId, {
          directiveId: _directiveId,
          nonce: _nonce,
          pin,
          deviceFingerprint: getDeviceFingerprint(),
          idempotencyKey: _idempotencyKey,
        })

        if (result.status === "settling") {
          // ── In-flight card (buy → pay-in; sell/send → settling) ──────────────
          let inFlight: ChatMessage
          if (result.payment) {
            const p = result.payment
            inFlight = {
              id: nextId(),
              role: "assistant",
              kind: "pay_in",
              transactionId: result.transactionId,
              accountNumber: p.accountNumber,
              bankName: p.bankName,
              providerRef: p.providerRef,
              amount: p.amount,
              currency: p.currency,
              status: "pending",
            }
          } else if (result.payout) {
            inFlight = {
              id: nextId(),
              role: "assistant",
              kind: "settling",
              txType: "sell",
              transactionId: result.transactionId,
              title: "Payout processing",
              subtitle: "Sending the funds to your bank account.",
              rows: pending.rows,
              reference: result.payout.providerRef,
              status: "pending",
            }
          } else {
            // send — result.onChain
            inFlight = {
              id: nextId(),
              role: "assistant",
              kind: "settling",
              txType: "send",
              transactionId: result.transactionId,
              title: "Transfer processing",
              subtitle: "Broadcasting your transfer on-chain.",
              rows: pending.rows,
              reference: result.onChain?.providerRef ?? "",
              status: "pending",
            }
          }

          set((s) => ({
            threads: {
              ...s.threads,
              [overlaySurface]: [...s.threads[overlaySurface], inFlight],
            },
            chips: { ...s.chips, [overlaySurface]: startChips() },
            pending: null,
            confirmOpen: false,
            pinError: null,
            _directiveId: null,
            _nonce: null,
            _idempotencyKey: null,
            _pollingTransactionId: result.transactionId,
          }))

          // Poll until completed/failed. setInterval so tests can spy/clear.
          const pollFn = getPollFn()!
          const action = pending.action
          const txId = result.transactionId
          const intervalId = setInterval(() => {
            void pollFn(txId).then((tx) => {
              if (tx.status === "completed") {
                clearInterval(intervalId)

                // Append a completed receipt (append-only thread — no mutation).
                const completedReceipt: ChatMessage = {
                  ...buildCompletionReceipt(action, pending, tx),
                  id: nextId(),
                  role: "assistant",
                }

                set((s) => ({
                  threads: {
                    ...s.threads,
                    [overlaySurface]: [
                      ...s.threads[overlaySurface],
                      completedReceipt,
                    ],
                  },
                  chips: { ...s.chips, [overlaySurface]: startChips() },
                  _pollingTransactionId: null,
                  successOpen: true,
                  successText: COMPLETION_SUCCESS_LABEL[action] ?? "Done",
                  successSurface: overlaySurface,
                }))

                setTimeout(() => {
                  set({ successOpen: false })
                }, SUCCESS_DISMISS_MS)
              } else if (tx.status === "failed") {
                clearInterval(intervalId)
                const failMsg: ChatMessage = {
                  id: nextId(),
                  role: "assistant",
                  kind: "text",
                  text: "This transaction could not be completed. No funds have left your wallet — please try again.",
                }
                set((s) => ({
                  threads: {
                    ...s.threads,
                    [overlaySurface]: [...s.threads[overlaySurface], failMsg],
                  },
                  chips: { ...s.chips, [overlaySurface]: startChips() },
                  _pollingTransactionId: null,
                }))
              }
            })
          }, POLL_INTERVAL_MS)
        } else {
          // ── Immediate completion path ────────────────────────────────────────
          const successText = COMPLETION_SUCCESS_LABEL[pending.action] ?? "Done"

          const receipt: ChatMessage = {
            ...buildReceipt(pending.action, pending.meta),
            id: nextId(),
            role: "assistant",
          }

          set((s) => ({
            threads: {
              ...s.threads,
              [overlaySurface]: [...s.threads[overlaySurface], receipt],
            },
            chips: { ...s.chips, [overlaySurface]: startChips() },
            pending: null,
            confirmOpen: false,
            pendingProposalId: null,
            pinError: null,
            _directiveId: null,
            _nonce: null,
            _idempotencyKey: null,
            successOpen: true,
            successText,
            successSurface: overlaySurface,
          }))

          setTimeout(() => {
            set({ successOpen: false })
          }, SUCCESS_DISMISS_MS)
        }
      } catch (err) {
        // Wrong PIN / locked / expired directive — re-open PIN pad so user can retry.
        // Keep the proposal alive; don't clear pendingProposalId.
        const message =
          err instanceof Error
            ? err.message
            : "Incorrect PIN or expired session. Please try again."
        set({
          pinOpen: true,
          pin: "",
          pinError: message,
        })
      }
    },

    reset(surface) {
      const greeting = greetingMessage(
        surface === "m" ? GREETING_M : GREETING_D
      )
      set((s) => ({
        threads: { ...s.threads, [surface]: [greeting] },
        chips: { ...s.chips, [surface]: startChips() },
        input: { ...s.input, [surface]: "" },
      }))
    },
  }))
}

// ─── React singleton binding ──────────────────────────────────────────────────

/**
 * Module-level singleton vanilla store — used by `useChatStore` and `MobileShell` default.
 * Components: `const state = useChatStore(selector)` or `useChatStore()` for full state.
 *
 * Separate from `createChatStore` so tests use fresh isolated stores.
 */
export const defaultChatStore = createChatStore()

export type ChatStore = ReturnType<typeof createChatStore>

/**
 * React hook bound to the module-default singleton chat store.
 *
 * @example
 *   const threads = useChatStore(s => s.threads)
 *   const send = useChatStore(s => s.send)
 */
export function useChatStore(): ChatState
export function useChatStore<U>(selector: (state: ChatState) => U): U
export function useChatStore<U>(
  selector?: (state: ChatState) => U
): U | ChatState {
  if (selector) {
    // eslint-disable-next-line react-hooks/rules-of-hooks
    return useStore(defaultChatStore, selector)
  }
  // eslint-disable-next-line react-hooks/rules-of-hooks
  return useStore(defaultChatStore)
}
