/**
 * Zustand chat store — Phase 9 of the Handshake Agent prototype.
 *
 * SACROSANCT INVARIANT (CLAUDE.md §3.1):
 * `pinComplete()` is the ONLY method that may append a receipt-kind message
 * and open the success overlay. No other action on this path (send, openConfirm,
 * confirmToPin, pressPin before the 4th digit) may ever produce a receipt.
 *
 * Real buy flow (authenticated):
 *   openConfirm → confirmToPin (calls authorizeProposal, stores directiveId+nonce)
 *   → pressPin × 4 → pinComplete (calls executeProposal with PIN)
 *   → on settle: appends pay-in card, polls getTransaction
 *   → on completed: appends full receipt card, opens success overlay
 *
 * Architecture notes:
 * - `createChatStore` is the testable vanilla factory (no React dependency).
 *   Tests inject `schedule: (fn) => fn()` so timers run synchronously.
 * - `useChatStore` is the module-default React binding (singleton store).
 * - Message IDs are generated by a per-store incrementing counter — no
 *   Math.random / Date (non-deterministic, disallowed per spec).
 */

import { createStore } from "zustand/vanilla"
import { useStore } from "zustand"
import {
  buildResponse,
  buildReceipt,
  startChips,
  chipLabel,
  actionPrompt,
} from "@/lib/chat/flow"
import { parseIntent } from "@/lib/chat/intent"
import { mapOutcomeToMessages } from "@/lib/chat/agent-outcome"
import { GREETING_M, GREETING_D, greetingDesktop } from "@/lib/constants"
import { isSessionExpiredError } from "@/lib/api/client"
import {
  buildCompletionReceipt,
  COMPLETION_SUCCESS_LABEL,
} from "@/lib/chat/completion-receipt"
import {
  chatErrorMessage,
  isRetryablePinError,
  SESSION_EXPIRED_NOTICE,
} from "@/lib/chat/errors"
import type {
  ChatAction,
  ChatMessage,
  ChatSurface,
  ConfirmPayload,
} from "@/lib/schemas"
import {
  sendChatMessage as defaultSendChatMessage,
  sendVoiceNote as defaultSendVoiceNote,
} from "@/lib/api/chat"
import type {
  WebChatResponse,
  VoiceChatResponse,
  ChatMessageRequest,
  ChatHistoryItem,
  AuthorizeProposalResponse,
  ExecuteProposalResponse,
  TransactionStatusResponse,
  SendDestinationInput,
} from "@handshake-agent/contracts"
import { getDeviceFingerprint } from "@/lib/device"

// Re-export chip/prompt helpers so surfaces can import them from the store
// module if needed. actionPrompt gives pages an amount-free open prompt to send
// to the live agent for authenticated quick-actions (finding #6).
export { chipLabel, actionPrompt }

/** Milliseconds before the success overlay auto-dismisses. Matches prototype (line 1352). */
const SUCCESS_DISMISS_MS = 1150

/**
 * Once a proposal is executed (buy → pay-in, or an instant completion), the
 * quote/swap card that spawned it must stop offering "Review & confirm" — a
 * spent quote's confirm would 409. Mark the most recent still-live quote/swap in
 * the thread terminal, mirroring what a reload does when GET /chat/messages
 * returns the proposal with status "executed".
 */
function markLatestProposalCardExecuted(thread: ChatMessage[]): ChatMessage[] {
  for (let i = thread.length - 1; i >= 0; i--) {
    const m = thread[i]
    if (
      (m.kind === "quote" || m.kind === "swap") &&
      m.proposalStatus !== "executed" &&
      m.proposalStatus !== "rejected"
    ) {
      const next = thread.slice()
      next[i] = { ...m, proposalStatus: "executed" }
      return next
    }
  }
  return thread
}

// ─── Scheduler type ───────────────────────────────────────────────────────────

/** A function that schedules `fn` to run after a typing delay (or immediately in tests). */
type Scheduler = (fn: () => void) => void

// ─── API adapters injected for testing ────────────────────────────────────────

interface ChatApis {
  chatApi?: (body: ChatMessageRequest) => Promise<WebChatResponse>
  authorizeApi?: (proposalId: string) => Promise<AuthorizeProposalResponse>
  executeApi?: (
    proposalId: string,
    body: {
      directiveId: string
      nonce: string
      pin: string
      deviceFingerprint?: string
      idempotencyKey: string
    }
  ) => Promise<ExecuteProposalResponse>
}

// ─── State interface ──────────────────────────────────────────────────────────

type OverlaySurface = ChatSurface

interface ChatState {
  // Per-surface state
  threads: Record<ChatSurface, ChatMessage[]>
  chips: Record<ChatSurface, ChatAction[]>
  typing: Record<ChatSurface, boolean>
  input: Record<ChatSurface, string>

  // Overlay state — one overlay at a time, surface-tracked
  pending: ConfirmPayload | null
  overlaySurface: OverlaySurface
  confirmOpen: boolean
  pinOpen: boolean
  pin: string
  successOpen: boolean
  successText: string
  successSurface: OverlaySurface

  // PIN error state — shown on the pin pad after a wrong PIN / expired directive
  pinError: string | null

  // Live agent proposal tracking
  pendingProposalId: string | null

  // Authorize step — stored between confirmToPin and pinComplete
  _directiveId: string | null
  _nonce: string | null
  _idempotencyKey: string | null

  // Settling: track the transaction being polled by the live card hook
  // (PayInCardLive for buy, SettlingCardLive for sell/send), plus the surface,
  // action, and confirmed payload so resolveSettlement can append the right
  // completion receipt / failure message to the correct thread.
  _pollingTransactionId: string | null
  _settlingSurface: OverlaySurface | null
  _settlingAction: ChatAction | null
  _settlingPending: ConfirmPayload | null

  // Per-surface flag: server history is hydrated once so re-renders / tab
  // switches don't re-append the thread.
  historyHydrated: Record<ChatSurface, boolean>

  // The last money-intent text the user sent — re-sent (with a beneficiaryId)
  // by resolveBeneficiary after they add a payout destination. Used only as the
  // fallback when a needs_beneficiary card does not pass its own message id.
  _lastIntentText: string | null

  // Finding #3: each needs_beneficiary / choose_beneficiary card is bound to
  // the EXACT intent text that produced it (keyed by the card's message id), so
  // resolving a stale card re-sends that intent — not whatever the user typed
  // most recently.
  _beneficiaryIntents: Record<string, string>

  // Actions
  send(surface: ChatSurface, text: string, action?: ChatAction): void
  /**
   * Sends `text` to the live agent. `opts.beneficiaryId` and
   * `opts.sendDestination` are mutually exclusive (the request contract's
   * `.refine` rejects both) — pass at most one. `sendDestination` is the
   * USER-confirmed raw on-chain destination captured by the send-mode card
   * (§3.1 — never fabricated client-side, forwarded verbatim).
   */
  sendToAgent(
    surface: ChatSurface,
    text: string,
    opts?: { beneficiaryId?: string; sendDestination?: SendDestinationInput }
  ): Promise<void>
  /**
   * Rebuild the thread from persisted server history (GET /chat/messages).
   * Idempotent per surface. Maps each turn with the same `mapOutcomeToMessages`
   * the live send uses, so reloaded cards match live cards. Never appends a
   * receipt (§3.1) and never touches overlay/pin state.
   */
  hydrateHistory(surface: ChatSurface, items: ChatHistoryItem[]): void
  /**
   * Re-sends the money request a specific needs_beneficiary or
   * choose_beneficiary card was created for, with a newly added/selected
   * beneficiaryId so the sell/send proposal can be created. Called from those
   * cards once the user adds or picks a payout destination.
   *
   * Finding #3: pass the card's `messageId` so the re-send uses the intent text
   * THAT card was bound to — not the mutable `_lastIntentText`, which a later
   * unrelated message would have overwritten. Omitting `messageId` falls back to
   * `_lastIntentText` (legacy callers).
   */
  resolveBeneficiary(
    surface: ChatSurface,
    beneficiaryId: string,
    messageId?: string
  ): Promise<void>
  /**
   * Re-sends the money request a needs_beneficiary card was created for, with
   * a raw user-confirmed on-chain destination instead of a saved beneficiary
   * id (crypto send-to-address path, Task 8's send-mode card). Mirrors
   * `resolveBeneficiary` exactly: looks up the intent text bound to `messageId`
   * via `_beneficiaryIntents`, falling back to `_lastIntentText` when no
   * messageId is passed (legacy callers).
   */
  resolveSendRaw(
    surface: ChatSurface,
    dest: SendDestinationInput,
    messageId?: string
  ): Promise<void>
  /** Wire (or replace) the dead-session redirect after construction (findings #1/#2). */
  setSessionExpiredHandler(handler: () => void): void
  /**
   * Wire (or replace) the on-completion cache-invalidation callback (Bug 3). The
   * store is not a React component, so the surface injects a callback that holds
   * a `queryClient` and invalidates the activity feed + balances when an execute
   * COMPLETES — otherwise those TanStack Query caches stay stale until a manual
   * page refresh. Fires only on a terminal `completed`, never on settling/failed.
   */
  setTransactionCompleteHandler(handler: () => void): void
  /**
   * Transcribe a recorded voice note (POST /chat/voice) and route the transcript
   * through the same agent path as text: appends the transcript as the user
   * bubble + the mapped outcome. Never appends a receipt (§3.1).
   */
  sendVoiceToAgent(surface: ChatSurface, blob: Blob): Promise<void>
  setInput(surface: ChatSurface, value: string): void
  /**
   * Personalize the desktop chat greeting with the signed-in user's first name
   * (matching the topbar's profile name). Called once the profile loads. A no-op
   * once the desktop conversation has started — it only swaps the initial
   * greeting message in place, never clobbering history. Passing no name leaves
   * the name-free generic greeting.
   */
  setDesktopGreeting(firstName?: string): void
  openConfirm(surface: ChatSurface, payload: ConfirmPayload): void
  cancel(): void
  /**
   * Calls authorizeProposal (authenticated flow) or falls back to PIN immediately
   * (mock/unauthenticated flow). Updates _directiveId + _nonce on success.
   */
  confirmToPin(): Promise<void>
  pressPin(digit: string): void
  pinBack(): void
  /** THE ONLY method that appends a receipt-kind message. */
  pinComplete(): Promise<void>
  /**
   * Resolve a settling buy when the live PayInCardLive poll reports a terminal
   * status. completed → append the receipt + open success; failed → surface the
   * failure in-thread. No-op for non-terminal statuses or an untracked tx
   * (idempotent — guards repeated hook fires). C4: the single settlement watcher
   * is the TanStack Query hook; this is its callback, not a second poller.
   */
  resolveSettlement(tx: TransactionStatusResponse): void
  reset(surface: ChatSurface): void
}

// ─── Options ──────────────────────────────────────────────────────────────────

interface CreateChatStoreOptions {
  /** Inject a custom scheduler. Default: `(fn) => setTimeout(fn, 680)`. */
  schedule?: Scheduler
  /**
   * Inject mock API functions for testing without module-level mocking.
   * Defaults to the real implementations from `@/lib/api/chat`.
   */
  chatApi?: (body: ChatMessageRequest) => Promise<WebChatResponse>
  authorizeApi?: ChatApis["authorizeApi"]
  executeApi?: ChatApis["executeApi"]
  /**
   * Inject a mock voice API function for testing `sendVoiceToAgent` without
   * module-level mocking. Defaults to `sendVoiceNote` from `@/lib/api/chat`.
   */
  voiceApi?: (blob: Blob) => Promise<VoiceChatResponse>
  /**
   * Called when a request fails with the dead-session 401 (findings #1 / #2).
   * The store cannot import `next/navigation`, so the surface injects a
   * redirect (e.g. `() => router.push("/login")`). May also be wired after
   * construction via `setSessionExpiredHandler`.
   */
  onSessionExpired?: () => void
  /**
   * Called when an execute COMPLETES (Bug 3) so the surface can invalidate the
   * activity feed + balances + transactions TanStack Query caches. The store
   * can't hold a `queryClient`, so the surface injects this. May also be wired
   * after construction via `setTransactionCompleteHandler`.
   */
  onTransactionComplete?: () => void
}

// ─── Factory ──────────────────────────────────────────────────────────────────

/**
 * Create a vanilla Zustand chat store.
 * Returns a `StoreApi<ChatState>` — use `.getState()` / `.setState()` / `.subscribe()`.
 *
 * @example (test)
 *   const store = createChatStore({ schedule: (fn) => fn() })
 *   store.getState().send("m", "Buy ₦50,000 of USDT", "buy")
 */
export function createChatStore(options: CreateChatStoreOptions = {}) {
  const schedule: Scheduler = options.schedule ?? ((fn) => setTimeout(fn, 680))
  const chatApiFn = options.chatApi ?? defaultSendChatMessage
  const voiceApiFn = options.voiceApi ?? defaultSendVoiceNote

  // Mutable redirect handler — set at construction and/or via
  // setSessionExpiredHandler. Default no-op so the store works headless (the
  // interceptor already clears the session, so RequireAuth redirects on its next
  // render even when no handler is wired).
  let onSessionExpired: () => void = options.onSessionExpired ?? (() => {})

  // Mutable completion handler (Bug 3) — set at construction and/or via
  // setTransactionCompleteHandler. Default no-op so the store works headless.
  let onTransactionComplete: () => void =
    options.onTransactionComplete ?? (() => {})

  // Lazy-import the real API functions so tests can inject mocks without
  // bundling the axios client. These are only called when the injected
  // override is absent — i.e. in the real app.
  const getAuthorizeFn = (): ChatApis["authorizeApi"] => {
    if (options.authorizeApi) return options.authorizeApi
    // Dynamic require to stay CJS-safe in tests; in the real app this is
    // bundled as ESM.  We import the module and pull the named export.
    return (proposalId: string) =>
      import("@/lib/api/chat").then((m) => m.authorizeProposal(proposalId))
  }

  const getExecuteFn = (): ChatApis["executeApi"] => {
    if (options.executeApi) return options.executeApi
    return (proposalId, body) =>
      import("@/lib/api/chat").then((m) => m.executeProposal(proposalId, body))
  }

  // Per-store monotonic counter — deterministic, no Math.random / Date.
  let _idCounter = 0
  function nextId(): string {
    return `msg-${++_idCounter}`
  }

  /** Build the initial greeting message for a surface. */
  function greetingMessage(text: string): ChatMessage {
    return { id: nextId(), role: "assistant", kind: "text", text }
  }

  const greetingM = greetingMessage(GREETING_M)
  const greetingD = greetingMessage(GREETING_D)

  return createStore<ChatState>()((set, get) => {
    /**
     * Shared dead-session handler (findings #1 / #2). Closes every overlay/pin
     * pad (a PIN can't fix a dead session), surfaces a clear in-thread notice,
     * clears typing, and fires the injected redirect. NEVER sets pinError — a
     * session expiry must not masquerade as a wrong PIN.
     */
    function handleSessionExpired(surface: ChatSurface) {
      const notice: ChatMessage = {
        id: nextId(),
        role: "assistant",
        kind: "text",
        text: SESSION_EXPIRED_NOTICE,
      }
      set((s) => ({
        threads: {
          ...s.threads,
          [surface]: [...s.threads[surface], notice],
        },
        typing: { ...s.typing, [surface]: false },
        chips: { ...s.chips, [surface]: startChips() },
        confirmOpen: false,
        pinOpen: false,
        pin: "",
        pinError: null,
        pending: null,
        _directiveId: null,
        _nonce: null,
        _idempotencyKey: null,
      }))
      onSessionExpired()
    }

    return {
      // ── Initial state ──────────────────────────────────────────────────────────
      threads: {
        m: [greetingM],
        d: [greetingD],
      },
      chips: {
        m: startChips(),
        d: startChips(),
      },
      typing: { m: false, d: false },
      input: { m: "", d: "" },

      pending: null,
      overlaySurface: "m",
      confirmOpen: false,
      pinOpen: false,
      pin: "",
      successOpen: false,
      successText: "",
      successSurface: "m",

      pinError: null,

      pendingProposalId: null,

      _directiveId: null,
      _nonce: null,
      _idempotencyKey: null,
      _pollingTransactionId: null,
      _settlingSurface: null,
      _settlingAction: null,
      _settlingPending: null,
      historyHydrated: { m: false, d: false },
      _lastIntentText: null,
      _beneficiaryIntents: {},

      // ── Actions ────────────────────────────────────────────────────────────────

      setSessionExpiredHandler(handler) {
        onSessionExpired = handler
      },

      setTransactionCompleteHandler(handler) {
        onTransactionComplete = handler
      },

      hydrateHistory(surface, items) {
        if (get().historyHydrated[surface]) return

        const built: ChatMessage[] = []
        let lastProposalId: string | null = null
        // Bind reloaded needs_beneficiary / choose_beneficiary cards to the
        // intent text that produced them (item.userText), exactly like the live
        // send path — otherwise resolving a card after a page reload is a
        // silent no-op (no bound intent, no _lastIntentText).
        const beneficiaryIntents: Record<string, string> = {}
        for (const item of items) {
          built.push({
            id: nextId(),
            role: "user",
            kind: "text",
            text: item.userText,
          })
          if (item.outcome) {
            const { messages, proposalId } = mapOutcomeToMessages(
              item.outcome,
              nextId
            )
            built.push(...messages)
            if (proposalId) lastProposalId = proposalId
            for (const m of messages) {
              if (
                m.kind === "needs_beneficiary" ||
                m.kind === "choose_beneficiary"
              ) {
                beneficiaryIntents[m.id] = item.userText
              }
            }
          }
        }

        set((s) => {
          // Keep the greeting at index 0; insert reconstructed history after it,
          // before any messages already added live this session.
          const [greeting, ...rest] = s.threads[surface]
          return {
            threads: {
              ...s.threads,
              [surface]: [greeting, ...built, ...rest],
            },
            historyHydrated: { ...s.historyHydrated, [surface]: true },
            _beneficiaryIntents: {
              ...s._beneficiaryIntents,
              ...beneficiaryIntents,
            },
            ...(lastProposalId ? { pendingProposalId: lastProposalId } : {}),
          }
        })
      },

      async sendToAgent(surface, text, opts) {
        const trimmed = text.trim()
        if (!trimmed) return

        // Remember the text so resolveBeneficiary can re-send it once the user
        // adds the payout destination a sell/send needs.
        set({ _lastIntentText: trimmed })

        const userMsg: ChatMessage = {
          id: nextId(),
          role: "user",
          kind: "text",
          text: trimmed,
        }

        set((s) => ({
          threads: {
            ...s.threads,
            [surface]: [...s.threads[surface], userMsg],
          },
          chips: { ...s.chips, [surface]: [] },
          typing: { ...s.typing, [surface]: true },
        }))

        try {
          // beneficiaryId and sendDestination are mutually exclusive (the
          // contract's ChatMessageRequestSchema `.refine` rejects both) —
          // build the body with at most one present.
          const body: ChatMessageRequest = opts?.beneficiaryId
            ? { text: trimmed, beneficiaryId: opts.beneficiaryId }
            : opts?.sendDestination
              ? { text: trimmed, sendDestination: opts.sendDestination }
              : { text: trimmed }
          const response = await chatApiFn(body)
          const { outcome } = response

          // Shared mapping — identical to the reload/hydration path so a live reply
          // and a reloaded reply render the same. Never produces a receipt (§3.1).
          const { messages, proposalId } = mapOutcomeToMessages(outcome, nextId)
          const pendingProposalId = proposalId ?? undefined

          // Finding #3: bind any needs_beneficiary / choose_beneficiary card to
          // the EXACT intent text that produced it, keyed by the card's message
          // id, so resolving a stale card later re-sends that intent and not a
          // more recent unrelated one.
          const beneficiaryCard = messages.find(
            (m) =>
              m.kind === "needs_beneficiary" || m.kind === "choose_beneficiary"
          )

          set((s) => ({
            threads: {
              ...s.threads,
              [surface]: [...s.threads[surface], ...messages],
            },
            typing: { ...s.typing, [surface]: false },
            chips: { ...s.chips, [surface]: startChips() },
            ...(pendingProposalId ? { pendingProposalId } : {}),
            ...(beneficiaryCard
              ? {
                  _beneficiaryIntents: {
                    ...s._beneficiaryIntents,
                    [beneficiaryCard.id]: trimmed,
                  },
                }
              : {}),
          }))
        } catch (err) {
          // Finding #2: a dead session mid-conversation must move the user to
          // re-auth, not render a dead-end bubble that silently loses the thread.
          if (isSessionExpiredError(err)) {
            handleSessionExpired(surface)
            return
          }
          const errMsg: ChatMessage = {
            id: nextId(),
            role: "assistant",
            kind: "text",
            text: chatErrorMessage(err),
          }
          set((s) => ({
            threads: {
              ...s.threads,
              [surface]: [...s.threads[surface], errMsg],
            },
            typing: { ...s.typing, [surface]: false },
            chips: { ...s.chips, [surface]: startChips() },
          }))
        }
      },

      async sendVoiceToAgent(surface, blob) {
        set((s) => ({
          chips: { ...s.chips, [surface]: [] },
          typing: { ...s.typing, [surface]: true },
        }))

        try {
          const response = await voiceApiFn(blob)
          const userMsg: ChatMessage = {
            id: nextId(),
            role: "user",
            kind: "text",
            text: response.transcript,
          }
          const { messages, proposalId } = mapOutcomeToMessages(
            response.outcome,
            nextId
          )
          const pendingProposalId = proposalId ?? undefined

          // The transcript IS the intent text — bind it exactly like the text
          // path does so a beneficiary card born from a voice note can be
          // resolved (finding #3), and keep _lastIntentText for legacy callers.
          const beneficiaryCard = messages.find(
            (m) =>
              m.kind === "needs_beneficiary" || m.kind === "choose_beneficiary"
          )

          set((s) => ({
            threads: {
              ...s.threads,
              [surface]: [...s.threads[surface], userMsg, ...messages],
            },
            typing: { ...s.typing, [surface]: false },
            chips: { ...s.chips, [surface]: startChips() },
            _lastIntentText: response.transcript,
            ...(pendingProposalId ? { pendingProposalId } : {}),
            ...(beneficiaryCard
              ? {
                  _beneficiaryIntents: {
                    ...s._beneficiaryIntents,
                    [beneficiaryCard.id]: response.transcript,
                  },
                }
              : {}),
          }))
        } catch (err) {
          if (isSessionExpiredError(err)) {
            handleSessionExpired(surface)
            return
          }
          const errMsg: ChatMessage = {
            id: nextId(),
            role: "assistant",
            kind: "text",
            text: chatErrorMessage(err),
          }
          set((s) => ({
            threads: {
              ...s.threads,
              [surface]: [...s.threads[surface], errMsg],
            },
            typing: { ...s.typing, [surface]: false },
            chips: { ...s.chips, [surface]: startChips() },
          }))
        }
      },

      async resolveBeneficiary(surface, beneficiaryId, messageId) {
        // Finding #3: prefer the intent bound to THIS card; fall back to the
        // mutable last-intent only for legacy callers that pass no messageId.
        const { _beneficiaryIntents, _lastIntentText } = get()
        const intentText =
          (messageId ? _beneficiaryIntents[messageId] : undefined) ??
          _lastIntentText
        if (!intentText) return
        await get().sendToAgent(surface, intentText, { beneficiaryId })
      },

      async resolveSendRaw(surface, dest, messageId) {
        // Mirrors resolveBeneficiary: prefer the intent bound to THIS card;
        // fall back to the mutable last-intent only for legacy callers that
        // pass no messageId.
        const { _beneficiaryIntents, _lastIntentText } = get()
        const intentText =
          (messageId ? _beneficiaryIntents[messageId] : undefined) ??
          _lastIntentText
        if (!intentText) return
        await get().sendToAgent(surface, intentText, { sendDestination: dest })
      },

      send(surface, text, explicitAction) {
        const trimmed = text.trim()
        if (!trimmed) return

        const action: ChatAction | null = explicitAction ?? parseIntent(trimmed)

        // Append the user message immediately.
        const userMsg: ChatMessage = {
          id: nextId(),
          role: "user",
          kind: "text",
          text: trimmed,
        }

        set((s) => ({
          threads: {
            ...s.threads,
            [surface]: [...s.threads[surface], userMsg],
          },
          chips: { ...s.chips, [surface]: [] },
          typing: { ...s.typing, [surface]: true },
        }))

        if (action) {
          schedule(() => {
            const { messages } = buildResponse(action)
            const assembled: ChatMessage[] = messages.map((m) => ({
              ...m,
              id: nextId(),
              role: "assistant" as const,
            }))

            // Follow-up chips: clear them while a quote is pending (quote actions);
            // restore startChips for non-quote actions (balance/receive/ticket).
            const hasQuote = assembled.some((m) => m.kind === "quote")
            const followUpChips = hasQuote ? [] : startChips()

            set((s) => ({
              threads: {
                ...s.threads,
                [surface]: [...s.threads[surface], ...assembled],
              },
              typing: { ...s.typing, [surface]: false },
              chips: { ...s.chips, [surface]: followUpChips },
            }))
          })
        } else {
          // Fallback: no recognised intent — generic assistant reply.
          schedule(() => {
            const fallbackMsg: ChatMessage = {
              id: nextId(),
              role: "assistant",
              kind: "text",
              text: "I didn't quite catch that. Try asking me to buy crypto, send money, check your balance, or find an event ticket.",
            }
            set((s) => ({
              threads: {
                ...s.threads,
                [surface]: [...s.threads[surface], fallbackMsg],
              },
              typing: { ...s.typing, [surface]: false },
              chips: { ...s.chips, [surface]: startChips() },
            }))
          })
        }
      },

      setInput(surface, value) {
        set((s) => ({ input: { ...s.input, [surface]: value } }))
      },

      setDesktopGreeting(firstName) {
        set((s) => {
          const thread = s.threads.d
          // Only swap the initial greeting — never once a conversation exists.
          if (thread.length !== 1) return s
          const [greeting] = thread
          return {
            threads: {
              ...s.threads,
              d: [{ ...greeting, text: greetingDesktop(firstName) }],
            },
          }
        })
      },

      openConfirm(surface, payload) {
        set({
          pending: payload,
          overlaySurface: surface,
          confirmOpen: true,
          pinError: null,
          _directiveId: null,
          _nonce: null,
          _idempotencyKey: null,
        })
      },

      cancel() {
        set({
          confirmOpen: false,
          pinOpen: false,
          pin: "",
          pending: null,
          pinError: null,
          _directiveId: null,
          _nonce: null,
          _idempotencyKey: null,
        })
      },

      /**
       * Transition from confirm sheet to PIN pad.
       *
       * Authenticated path: calls authorizeProposal(pendingProposalId) first.
       * On success, stores directiveId + nonce + fresh idempotencyKey, then
       * opens the PIN pad. On failure, surface the error on the confirm sheet
       * and keep it open so the user can retry or cancel.
       *
       * Mock/unauthenticated path: pendingProposalId is null → open PIN directly.
       */
      async confirmToPin() {
        const { pendingProposalId } = get()

        // Mock/offline path (no live proposal): skip authorize, open PIN directly.
        if (!pendingProposalId) {
          set({ confirmOpen: false, pinOpen: true, pin: "", pinError: null })
          return
        }

        try {
          const authorizeFn = getAuthorizeFn()!
          const result = await authorizeFn(pendingProposalId)
          set({
            confirmOpen: false,
            pinOpen: true,
            pin: "",
            pinError: null,
            _directiveId: result.directiveId,
            _nonce: result.nonce,
            // I8: the execute idempotency key is STABLE per proposal (= proposalId),
            // not a fresh uuid per attempt. A retry of the same proposal therefore
            // sends the same key, and the server (which derives the same key from
            // proposalId, never trusting this value) dedups it — no double-execute.
            _idempotencyKey: pendingProposalId,
          })
        } catch (err) {
          // Finding #1: a dead session at the authorize step must not surface as a
          // confirm-sheet error the user can retry — take them to re-auth.
          if (isSessionExpiredError(err)) {
            handleSessionExpired(get().overlaySurface)
            return
          }
          // Show error on the confirm sheet; do NOT open the PIN pad.
          const message =
            err instanceof Error
              ? err.message
              : "Authorization failed. Please try again."
          set({ pinError: message })
        }
      },

      pressPin(digit) {
        const { pin } = get()
        // Ignore if already 4 digits — this guard is checked against the current
        // pin length BEFORE appending, so pressing a 5th digit when pin === "1234"
        // (length 4) is ignored. After pinComplete() runs, pin resets to "" so
        // subsequent presses start a fresh entry.
        if (pin.length >= 4) return
        const next = pin + digit
        set({ pin: next })
        if (next.length === 4) {
          void get().pinComplete()
        }
      },

      pinBack() {
        set((s) => ({ pin: s.pin.slice(0, -1) }))
      },

      /**
       * THE ONLY path that appends a receipt-kind message and opens success.
       * Called automatically when the 4th PIN digit is pressed.
       *
       * Authenticated path: calls executeProposal with PIN + directive credentials.
       * - status:"settling" + payment → appends pay-in card, starts polling.
       * - status:"completed" → appends full receipt, opens success overlay.
       * - Wrong PIN / expired / locked → clears PIN, shows error on PIN pad, keeps proposal.
       *
       * Mock/offline path (_directiveId is null): appends fixture receipt immediately.
       */
      async pinComplete() {
        const {
          pending,
          overlaySurface,
          pendingProposalId,
          _directiveId,
          _nonce,
          _idempotencyKey,
          pin,
        } = get()
        if (!pending) return

        // ── Mock/offline path ────────────────────────────────────────────────────
        if (
          !pendingProposalId ||
          !_directiveId ||
          !_nonce ||
          !_idempotencyKey
        ) {
          const receipt: ChatMessage = {
            ...buildReceipt(pending.action, pending.meta),
            id: nextId(),
            role: "assistant",
          }

          const successText = COMPLETION_SUCCESS_LABEL[pending.action] ?? "Done"

          set((s) => ({
            threads: {
              ...s.threads,
              [overlaySurface]: [...s.threads[overlaySurface], receipt],
            },
            chips: { ...s.chips, [overlaySurface]: startChips() },
            pinOpen: false,
            pin: "",
            confirmOpen: false,
            pending: null,
            pendingProposalId: null,
            pinError: null,
            _directiveId: null,
            _nonce: null,
            _idempotencyKey: null,
            successOpen: true,
            successText,
            successSurface: overlaySurface,
          }))

          setTimeout(() => {
            set({ successOpen: false })
          }, SUCCESS_DISMISS_MS)
          return
        }

        // ── Authenticated path ───────────────────────────────────────────────────
        // Close the PIN pad immediately (provides instant feedback)
        set({ pinOpen: false, pin: "" })

        try {
          const executeFn = getExecuteFn()!
          const result = await executeFn(pendingProposalId, {
            directiveId: _directiveId,
            nonce: _nonce,
            pin,
            deviceFingerprint: getDeviceFingerprint(),
            idempotencyKey: _idempotencyKey,
          })

          if (result.status === "settling") {
            // ── In-flight card (buy → pay-in; sell/send → settling) ──────────────
            let inFlight: ChatMessage
            if (result.payment) {
              const p = result.payment
              inFlight = {
                id: nextId(),
                role: "assistant",
                kind: "pay_in",
                transactionId: result.transactionId,
                accountNumber: p.accountNumber,
                bankName: p.bankName,
                providerRef: p.providerRef,
                amount: p.amount,
                currency: p.currency,
                status: "pending",
              }
            } else if (result.payout) {
              inFlight = {
                id: nextId(),
                role: "assistant",
                kind: "settling",
                txType: "sell",
                transactionId: result.transactionId,
                title: "Payout processing",
                subtitle: "Sending the funds to your bank account.",
                rows: pending.rows,
                reference: result.payout.providerRef,
                status: "pending",
              }
            } else if (result.swap) {
              // Finding #4: a swap that returns 'settling' must render a SWAP card
              // with swap copy — not fall through to the send branch's
              // "Broadcasting your transfer on-chain." (which mislabels the action
              // on the in-flight card AND the completion receipt). SettlingView's
              // txType now includes "swap" (web/lib/schemas/chat.ts), so this is a
              // plain ChatMessage — no cast.
              inFlight = {
                id: nextId(),
                role: "assistant",
                kind: "settling",
                txType: "swap",
                transactionId: result.transactionId,
                title: "Swap processing",
                subtitle: "Completing your swap on-chain.",
                rows: pending.rows,
                reference: result.swap.providerSwapId,
                status: "pending",
              }
            } else {
              // send — result.onChain
              inFlight = {
                id: nextId(),
                role: "assistant",
                kind: "settling",
                txType: "send",
                transactionId: result.transactionId,
                title: "Transfer processing",
                subtitle: "Broadcasting your transfer on-chain.",
                rows: pending.rows,
                reference: result.onChain?.providerRef ?? "",
                status: "pending",
              }
            }

            // C4: hand polling off to the live PayInCardLive TanStack Query hook —
            // the single settlement watcher (stops on completed/failed, clears on
            // unmount). The store NO LONGER runs a setInterval (which leaked: it
            // polled forever on a failed settlement and swallowed the failure).
            // Record the tx id + surface so resolveSettlement (the hook's callback)
            // can append the terminal receipt/failure to the right thread.
            set((s) => ({
              threads: {
                ...s.threads,
                [overlaySurface]: [
                  ...markLatestProposalCardExecuted(s.threads[overlaySurface]),
                  inFlight,
                ],
              },
              chips: { ...s.chips, [overlaySurface]: startChips() },
              pending: null,
              confirmOpen: false,
              pinError: null,
              _directiveId: null,
              _nonce: null,
              _idempotencyKey: null,
              _pollingTransactionId: result.transactionId,
              _settlingSurface: overlaySurface,
              // C4: record the action + confirmed payload so resolveSettlement (the
              // live card hook's callback) can build the right buy/sell/send receipt
              // on completion — no store setInterval is started here.
              _settlingAction: pending.action,
              _settlingPending: pending,
            }))
          } else {
            // ── Immediate completion path ────────────────────────────────────────
            const successText =
              COMPLETION_SUCCESS_LABEL[pending.action] ?? "Done"

            // Build the receipt from the CONFIRMED payload — mirroring the
            // settling path's resolveSettlement — never the demo buildReceipt
            // fixture (which carries hardcoded ₦50,000 rows and a fake ref).
            // The execute response has no status payload, so synthesize the
            // minimal terminal TransactionStatusResponse from what we know.
            const completedTx: TransactionStatusResponse = {
              id: result.transactionId,
              type: pending.action,
              status: "completed",
              createdAt: new Date().toISOString(),
            }
            const receipt: ChatMessage = {
              ...buildCompletionReceipt(pending.action, pending, completedTx),
              id: nextId(),
              role: "assistant",
            }

            set((s) => ({
              threads: {
                ...s.threads,
                [overlaySurface]: [
                  ...markLatestProposalCardExecuted(s.threads[overlaySurface]),
                  receipt,
                ],
              },
              chips: { ...s.chips, [overlaySurface]: startChips() },
              pending: null,
              confirmOpen: false,
              pendingProposalId: null,
              pinError: null,
              _directiveId: null,
              _nonce: null,
              _idempotencyKey: null,
              successOpen: true,
              successText,
              successSurface: overlaySurface,
            }))

            // Bug 3: an execute that completes instantly (e.g. an internal
            // transfer) never hands off to the settlement watcher, so the
            // activity feed + balances would stay stale until a manual refresh.
            // Invalidate those caches here via the injected callback.
            onTransactionComplete()

            setTimeout(() => {
              set({ successOpen: false })
            }, SUCCESS_DISMISS_MS)
          }
        } catch (err) {
          // Finding #1: a dead session must NOT re-open the PIN pad — a PIN can't
          // fix an expired session. Close the overlays and route to re-auth.
          if (isSessionExpiredError(err)) {
            handleSessionExpired(overlaySurface)
            return
          }

          // A genuine PIN / directive failure (PIN_INVALID, PIN_LOCKED,
          // DIRECTIVE_EXPIRED → 401, or a bare Error from the mock path) IS fixable
          // by re-entering the PIN → re-open the pad with the error. Keep the
          // proposal alive; don't clear pendingProposalId.
          if (isRetryablePinError(err)) {
            const message =
              err instanceof Error
                ? err.message
                : "Incorrect PIN or expired session. Please try again."
            set({
              pinOpen: true,
              pin: "",
              pinError: message,
            })
            return
          }

          // Finding #5: every OTHER execute failure — quote drift (422),
          // swap-unavailable (503), insufficient balance (422), proposal expired,
          // conflict — is NOT a PIN problem and re-entering the PIN cannot fix it.
          // Surface the real cause as an assistant message and CLOSE the pad
          // instead of falsely prompting "Incorrect PIN or expired session".
          const errMsg: ChatMessage = {
            id: nextId(),
            role: "assistant",
            kind: "text",
            text: chatErrorMessage(err),
          }
          set((s) => ({
            threads: {
              ...s.threads,
              [overlaySurface]: [...s.threads[overlaySurface], errMsg],
            },
            chips: { ...s.chips, [overlaySurface]: startChips() },
            pinOpen: false,
            pin: "",
            confirmOpen: false,
            pinError: null,
          }))
        }
      },

      resolveSettlement(tx) {
        const {
          _pollingTransactionId,
          _settlingSurface,
          _settlingAction,
          _settlingPending,
        } = get()

        // Guard: only the currently-tracked settling tx, only on a terminal status.
        // Clearing the tracking on resolve makes repeated hook fires no-ops.
        if (
          _settlingSurface === null ||
          _settlingAction === null ||
          _settlingPending === null ||
          tx.id !== _pollingTransactionId ||
          (tx.status !== "completed" && tx.status !== "failed")
        ) {
          return
        }
        const surface = _settlingSurface

        if (tx.status === "completed") {
          // Build the buy / sell / send completion receipt from the action +
          // confirmed payload captured at handoff (sell/send amounts aren't echoed
          // on the status payload, so they come from `pending`).
          const completedReceipt: ChatMessage = {
            ...buildCompletionReceipt(_settlingAction, _settlingPending, tx),
            id: nextId(),
            role: "assistant",
          }

          set((s) => ({
            threads: {
              ...s.threads,
              [surface]: [...s.threads[surface], completedReceipt],
            },
            chips: { ...s.chips, [surface]: startChips() },
            _pollingTransactionId: null,
            _settlingSurface: null,
            _settlingAction: null,
            _settlingPending: null,
            successOpen: true,
            successText: COMPLETION_SUCCESS_LABEL[_settlingAction] ?? "Done",
            successSurface: surface,
          }))

          // Bug 3: a settled transaction changes balances + the activity feed —
          // invalidate those caches so the UI refreshes without a manual reload.
          onTransactionComplete()

          setTimeout(() => {
            set({ successOpen: false })
          }, SUCCESS_DISMISS_MS)
          return
        }

        // status === "failed": surface it in-thread (never swallow / poll forever).
        const failureMsg: ChatMessage = {
          id: nextId(),
          role: "assistant",
          kind: "text",
          text: "This transaction could not be completed. No funds have left your wallet — please try again.",
        }

        set((s) => ({
          threads: {
            ...s.threads,
            [surface]: [...s.threads[surface], failureMsg],
          },
          chips: { ...s.chips, [surface]: startChips() },
          _pollingTransactionId: null,
          _settlingSurface: null,
          _settlingAction: null,
          _settlingPending: null,
        }))
      },

      reset(surface) {
        const greeting = greetingMessage(
          surface === "m" ? GREETING_M : GREETING_D
        )
        set((s) => ({
          threads: { ...s.threads, [surface]: [greeting] },
          chips: { ...s.chips, [surface]: startChips() },
          input: { ...s.input, [surface]: "" },
        }))
      },
    }
  })
}

// ─── React singleton binding ──────────────────────────────────────────────────

/**
 * Module-level singleton vanilla store — used by `useChatStore` and `MobileShell` default.
 * Components: `const state = useChatStore(selector)` or `useChatStore()` for full state.
 *
 * Separate from `createChatStore` so tests use fresh isolated stores.
 */
export const defaultChatStore = createChatStore()

export type ChatStore = ReturnType<typeof createChatStore>

/**
 * React hook bound to the module-default singleton chat store.
 *
 * @example
 *   const threads = useChatStore(s => s.threads)
 *   const send = useChatStore(s => s.send)
 */
export function useChatStore(): ChatState
export function useChatStore<U>(selector: (state: ChatState) => U): U
export function useChatStore<U>(
  selector?: (state: ChatState) => U
): U | ChatState {
  if (selector) {
    // eslint-disable-next-line react-hooks/rules-of-hooks
    return useStore(defaultChatStore, selector)
  }
  // eslint-disable-next-line react-hooks/rules-of-hooks
  return useStore(defaultChatStore)
}
