/**
 * Zustand chat store — Phase 9 of the Handshake Agent prototype.
 *
 * SACROSANCT INVARIANT (CLAUDE.md §3.1):
 * `pinComplete()` is the ONLY method that may append a receipt-kind message
 * and open the success overlay. No other action on this path (send, openConfirm,
 * confirmToPin, pressPin before the 4th digit) may ever produce a receipt.
 *
 * Architecture notes:
 * - `createChatStore` is the testable vanilla factory (no React dependency).
 *   Tests inject `schedule: (fn) => fn()` so timers run synchronously.
 * - `useChatStore` is the module-default React binding (singleton store).
 * - Message IDs are generated by a per-store incrementing counter — no
 *   Math.random / Date (non-deterministic, disallowed per spec).
 */

import { createStore } from "zustand/vanilla"
import { useStore } from "zustand"
import {
  buildResponse,
  buildReceipt,
  startChips,
  chipLabel,
} from "@/lib/chat/flow"
import { parseIntent } from "@/lib/chat/intent"
import { GREETING_M, GREETING_D } from "@/lib/constants"
import type {
  ChatAction,
  ChatMessage,
  ChatSurface,
  ConfirmPayload,
} from "@/lib/schemas"
import { sendChatMessage as defaultSendChatMessage } from "@/lib/api/chat"
import type {
  WebChatResponse,
  BuyProposalConfirmation,
  SellProposalConfirmation,
  SendProposalConfirmation,
} from "@handshake-agent/contracts"

// Re-export chipLabel so components can import it from the store module if needed.
export { chipLabel }

/** Milliseconds before the success overlay auto-dismisses. Matches prototype (line 1352). */
const SUCCESS_DISMISS_MS = 1150

// ─── Scheduler type ───────────────────────────────────────────────────────────

/** A function that schedules `fn` to run after a typing delay (or immediately in tests). */
type Scheduler = (fn: () => void) => void

// ─── State interface ──────────────────────────────────────────────────────────

type OverlaySurface = ChatSurface

interface ChatState {
  // Per-surface state
  threads: Record<ChatSurface, ChatMessage[]>
  chips: Record<ChatSurface, ChatAction[]>
  typing: Record<ChatSurface, boolean>
  input: Record<ChatSurface, string>

  // Overlay state — one overlay at a time, surface-tracked
  pending: ConfirmPayload | null
  overlaySurface: OverlaySurface
  confirmOpen: boolean
  pinOpen: boolean
  pin: string
  successOpen: boolean
  successText: string
  successSurface: OverlaySurface

  // Live agent proposal tracking
  pendingProposalId: string | null

  // Actions
  send(surface: ChatSurface, text: string, action?: ChatAction): void
  sendToAgent(surface: ChatSurface, text: string): Promise<void>
  setInput(surface: ChatSurface, value: string): void
  openConfirm(surface: ChatSurface, payload: ConfirmPayload): void
  cancel(): void
  confirmToPin(): void
  pressPin(digit: string): void
  pinBack(): void
  /** THE ONLY method that appends a receipt-kind message. */
  pinComplete(): void
  reset(surface: ChatSurface): void
}

// ─── Options ──────────────────────────────────────────────────────────────────

interface CreateChatStoreOptions {
  /** Inject a custom scheduler. Default: `(fn) => setTimeout(fn, 680)`. */
  schedule?: Scheduler
  /**
   * Inject a mock API function for testing `sendToAgent` without module-level
   * mocking. Defaults to the real `sendChatMessage` from `@/lib/api/chat`.
   */
  chatApi?: (body: { text: string }) => Promise<WebChatResponse>
}

// ─── Factory ──────────────────────────────────────────────────────────────────

/**
 * Create a vanilla Zustand chat store.
 * Returns a `StoreApi<ChatState>` — use `.getState()` / `.setState()` / `.subscribe()`.
 *
 * @example (test)
 *   const store = createChatStore({ schedule: (fn) => fn() })
 *   store.getState().send("m", "Buy ₦50,000 of USDT", "buy")
 */
export function createChatStore(options: CreateChatStoreOptions = {}) {
  const schedule: Scheduler = options.schedule ?? ((fn) => setTimeout(fn, 680))
  const chatApiFn = options.chatApi ?? defaultSendChatMessage

  // Per-store monotonic counter — deterministic, no Math.random / Date.
  let _idCounter = 0
  function nextId(): string {
    return `msg-${++_idCounter}`
  }

  /** Build the initial greeting message for a surface. */
  function greetingMessage(text: string): ChatMessage {
    return { id: nextId(), role: "assistant", kind: "text", text }
  }

  const greetingM = greetingMessage(GREETING_M)
  const greetingD = greetingMessage(GREETING_D)

  return createStore<ChatState>()((set, get) => ({
    // ── Initial state ──────────────────────────────────────────────────────────
    threads: {
      m: [greetingM],
      d: [greetingD],
    },
    chips: {
      m: startChips(),
      d: startChips(),
    },
    typing: { m: false, d: false },
    input: { m: "", d: "" },

    pending: null,
    overlaySurface: "m",
    confirmOpen: false,
    pinOpen: false,
    pin: "",
    successOpen: false,
    successText: "",
    successSurface: "m",

    pendingProposalId: null,

    // ── Actions ────────────────────────────────────────────────────────────────

    async sendToAgent(surface, text) {
      const trimmed = text.trim()
      if (!trimmed) return

      const userMsg: ChatMessage = {
        id: nextId(),
        role: "user",
        kind: "text",
        text: trimmed,
      }

      set((s) => ({
        threads: { ...s.threads, [surface]: [...s.threads[surface], userMsg] },
        chips: { ...s.chips, [surface]: [] },
        typing: { ...s.typing, [surface]: true },
      }))

      try {
        const response = await chatApiFn({ text: trimmed })
        const { outcome } = response

        const messages: ChatMessage[] = []

        if (outcome.kind === "clarification") {
          messages.push({
            id: nextId(),
            role: "assistant",
            kind: "text",
            text: outcome.text,
          })
        } else if (outcome.kind === "receive") {
          const d = outcome.deposit
          messages.push({
            id: nextId(),
            role: "assistant",
            kind: "receive",
            asset: d.asset,
            network: d.network,
            address: d.address,
            minDeposit: d.minAmount ?? "—",
            creditedEta: d.etaText ?? "~30 min",
          })
        } else if (outcome.kind === "proposal") {
          const c = outcome.confirmation
          const rows: Array<{ label: string; value: string }> = []
          let receiveAmt = ""
          let receiveSub = ""
          let totalLabel = "Total"
          let totalValue = ""
          const lockSeconds = Math.max(
            0,
            Math.round((new Date(c.expiresAt).getTime() - Date.now()) / 1000)
          )

          if (outcome.txType === "buy") {
            const b = c as BuyProposalConfirmation
            receiveAmt = b.cryptoAmount + " " + b.asset
            receiveSub = "You receive"
            rows.push({
              label: "You pay",
              value: b.fiatCurrency + " " + b.fiatAmount,
            })
            rows.push({
              label: "Rate",
              value: "1 " + b.asset + " = " + b.fiatCurrency + " " + b.fxRate,
            })
            rows.push({
              label: "Fee",
              value: b.fiatCurrency + " " + b.processingFeeAmount,
            })
            totalLabel = "Total charged"
            totalValue = b.fiatCurrency + " " + b.totalFiat
          } else if (outcome.txType === "sell") {
            const s = c as SellProposalConfirmation
            receiveAmt = s.fiatCurrency + " " + s.netFiatAmount
            receiveSub = "You receive"
            rows.push({
              label: "You sell",
              value: s.cryptoAmount + " " + s.asset,
            })
            rows.push({
              label: "Rate",
              value: "1 " + s.asset + " = " + s.fiatCurrency + " " + s.fxRate,
            })
            rows.push({
              label: "Fee",
              value: s.fiatCurrency + " " + s.processingFeeAmount,
            })
            if (s.beneficiaryLabel) {
              rows.push({ label: "To", value: s.beneficiaryLabel })
            }
            totalLabel = "Net payout"
            totalValue = s.fiatCurrency + " " + s.netFiatAmount
          } else if (outcome.txType === "send") {
            const sn = c as SendProposalConfirmation
            receiveAmt = sn.cryptoAmount + " " + sn.asset
            receiveSub = "Amount sent"
            rows.push({ label: "To", value: sn.toAddressMasked })
            if (sn.beneficiaryLabel) {
              rows.push({ label: "Beneficiary", value: sn.beneficiaryLabel })
            }
            rows.push({ label: "Network", value: sn.network })
            rows.push({
              label: "Network fee",
              value: sn.networkFeeCrypto + " " + sn.asset,
            })
            totalLabel = "Total debit"
            totalValue = sn.totalDebit + " " + sn.asset
          }

          messages.push({
            id: nextId(),
            role: "assistant",
            kind: "quote",
            // send is a valid ChatAction; buy and sell are also valid
            action: outcome.txType as ChatAction,
            receiveAmt,
            receiveSub,
            rows,
            totalLabel,
            totalValue,
            lockSeconds,
          })

          // Stash proposalId for the future execute phase.
          set({ pendingProposalId: outcome.proposalId })
        } else if (outcome.kind === "needs_kyc") {
          messages.push({
            id: nextId(),
            role: "assistant",
            kind: "text",
            text: "You need to complete verification first.",
          })
        } else if (outcome.kind === "needs_beneficiary") {
          messages.push({
            id: nextId(),
            role: "assistant",
            kind: "text",
            text: `Please add a ${
              outcome.beneficiaryType === "bank_account"
                ? "bank account"
                : "crypto address"
            } first.`,
          })
        } else if (outcome.kind === "not_supported") {
          messages.push({
            id: nextId(),
            role: "assistant",
            kind: "text",
            text: "That's not supported yet.",
          })
        }

        set((s) => ({
          threads: {
            ...s.threads,
            [surface]: [...s.threads[surface], ...messages],
          },
          typing: { ...s.typing, [surface]: false },
          chips: { ...s.chips, [surface]: startChips() },
        }))
      } catch {
        const errMsg: ChatMessage = {
          id: nextId(),
          role: "assistant",
          kind: "text",
          text: "I'm having trouble reaching the assistant right now — please try again.",
        }
        set((s) => ({
          threads: {
            ...s.threads,
            [surface]: [...s.threads[surface], errMsg],
          },
          typing: { ...s.typing, [surface]: false },
          chips: { ...s.chips, [surface]: startChips() },
        }))
      }
    },

    send(surface, text, explicitAction) {
      const trimmed = text.trim()
      if (!trimmed) return

      const action: ChatAction | null = explicitAction ?? parseIntent(trimmed)

      // Append the user message immediately.
      const userMsg: ChatMessage = {
        id: nextId(),
        role: "user",
        kind: "text",
        text: trimmed,
      }

      set((s) => ({
        threads: {
          ...s.threads,
          [surface]: [...s.threads[surface], userMsg],
        },
        chips: { ...s.chips, [surface]: [] },
        typing: { ...s.typing, [surface]: true },
      }))

      if (action) {
        schedule(() => {
          const { messages } = buildResponse(action)
          const assembled: ChatMessage[] = messages.map((m) => ({
            ...m,
            id: nextId(),
            role: "assistant" as const,
          }))

          // Follow-up chips: clear them while a quote is pending (quote actions);
          // restore startChips for non-quote actions (balance/receive/ticket).
          const hasQuote = assembled.some((m) => m.kind === "quote")
          const followUpChips = hasQuote ? [] : startChips()

          set((s) => ({
            threads: {
              ...s.threads,
              [surface]: [...s.threads[surface], ...assembled],
            },
            typing: { ...s.typing, [surface]: false },
            chips: { ...s.chips, [surface]: followUpChips },
          }))
        })
      } else {
        // Fallback: no recognised intent — generic assistant reply.
        schedule(() => {
          const fallbackMsg: ChatMessage = {
            id: nextId(),
            role: "assistant",
            kind: "text",
            text: "I didn't quite catch that. Try asking me to buy crypto, send money, check your balance, or find an event ticket.",
          }
          set((s) => ({
            threads: {
              ...s.threads,
              [surface]: [...s.threads[surface], fallbackMsg],
            },
            typing: { ...s.typing, [surface]: false },
            chips: { ...s.chips, [surface]: startChips() },
          }))
        })
      }
    },

    setInput(surface, value) {
      set((s) => ({ input: { ...s.input, [surface]: value } }))
    },

    openConfirm(surface, payload) {
      set({
        pending: payload,
        overlaySurface: surface,
        confirmOpen: true,
      })
    },

    cancel() {
      set({
        confirmOpen: false,
        pinOpen: false,
        pin: "",
        pending: null,
      })
    },

    confirmToPin() {
      set({ confirmOpen: false, pinOpen: true, pin: "" })
    },

    pressPin(digit) {
      const { pin } = get()
      // Ignore if already 4 digits — this guard is checked against the current
      // pin length BEFORE appending, so pressing a 5th digit when pin === "1234"
      // (length 4) is ignored. After pinComplete() runs, pin resets to "" so
      // subsequent presses start a fresh entry.
      if (pin.length >= 4) return
      const next = pin + digit
      set({ pin: next })
      if (next.length === 4) {
        get().pinComplete()
      }
    },

    pinBack() {
      set((s) => ({ pin: s.pin.slice(0, -1) }))
    },

    /**
     * THE ONLY path that appends a receipt-kind message and opens success.
     * Called automatically when the 4th PIN digit is pressed.
     * No other action may call this or replicate its effect.
     */
    pinComplete() {
      const { pending, overlaySurface } = get()
      if (!pending) return

      const receipt: ChatMessage = {
        ...buildReceipt(pending.action, pending.meta),
        id: nextId(),
        role: "assistant",
      }

      // Success label derived from the action.
      const successLabels: Record<ChatAction, string> = {
        buy: "Purchase complete",
        send: "Transfer sent",
        swap: "Swap complete",
        ticket: "Ticket confirmed",
        receive: "Deposit address shown",
        balance: "Balance loaded",
      }
      const successText = successLabels[pending.action] ?? "Done"

      set((s) => ({
        threads: {
          ...s.threads,
          [overlaySurface]: [...s.threads[overlaySurface], receipt],
        },
        chips: { ...s.chips, [overlaySurface]: startChips() },
        pinOpen: false,
        pin: "",
        confirmOpen: false,
        pending: null,
        successOpen: true,
        successText,
        successSurface: overlaySurface,
      }))

      // Auto-dismiss the success overlay after SUCCESS_DISMISS_MS (matches prototype).
      // We use a plain setTimeout here (not the injected `schedule`) so that
      // the injected synchronous scheduler used in tests does not immediately
      // dismiss the overlay — tests can assert `successOpen === true` after
      // pressing 4 digits, and separately assert auto-dismiss via a dedicated test.
      setTimeout(() => {
        set({ successOpen: false })
      }, SUCCESS_DISMISS_MS)
    },

    reset(surface) {
      const greeting = greetingMessage(
        surface === "m" ? GREETING_M : GREETING_D
      )
      set((s) => ({
        threads: { ...s.threads, [surface]: [greeting] },
        chips: { ...s.chips, [surface]: startChips() },
        input: { ...s.input, [surface]: "" },
      }))
    },
  }))
}

// ─── React singleton binding ──────────────────────────────────────────────────

/**
 * Module-level singleton vanilla store — used by `useChatStore` and `MobileShell` default.
 * Components: `const state = useChatStore(selector)` or `useChatStore()` for full state.
 *
 * Separate from `createChatStore` so tests use fresh isolated stores.
 */
export const defaultChatStore = createChatStore()

export type ChatStore = ReturnType<typeof createChatStore>

/**
 * React hook bound to the module-default singleton chat store.
 *
 * @example
 *   const threads = useChatStore(s => s.threads)
 *   const send = useChatStore(s => s.send)
 */
export function useChatStore(): ChatState
export function useChatStore<U>(selector: (state: ChatState) => U): U
export function useChatStore<U>(
  selector?: (state: ChatState) => U
): U | ChatState {
  if (selector) {
    // eslint-disable-next-line react-hooks/rules-of-hooks
    return useStore(defaultChatStore, selector)
  }
  // eslint-disable-next-line react-hooks/rules-of-hooks
  return useStore(defaultChatStore)
}
